[project]
name = "v1-with-antirobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pip>=25.1.1",
    "webdriver-manager>=4.0.2",
]
