[default]
Appointment_idx = 4 # Index of the appointment to check, starting from 0
HEADLESS = false # Set to true if you want to run hide the browser window
SERVICE_ID = "10339027"
LOCATION_ID = "10187259"
TARGET_DATE = "2025-08-15"
TIMEOUT = 15 # how long to wait for the shadow element to appear
BREAK_INTERVAL = 1 # how long to wait before checking again
RESTART_INTERVAL = 5 # how long to wait before restarting the program if error occurs
KontaktClick = true # Set to true if you want to click the contact button
proxy = false # Set to true if you want to use a proxy

